[package]
name = "ic_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfn_core = { git="https://github.com/dfinity/ic" }
dfn_candid = { git="https://github.com/dfinity/ic" }
candid = "0.6.15"
